"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, MoreHorizontal, X } from "lucide-react";
import { clientApis } from "@/lib/api/client-apis";
import { ApiError } from "@/lib/api/errors";
import type { ChatMessageDto, ChatRoomDto, ChatUserSearchDto, CourseDto } from "@/types/api";
import { ChatRoomList, roomLabel } from "@/components/chat/chat-room-list";
import { ChatMessageList } from "@/components/chat/chat-message-list";
import { ChatComposer } from "@/components/chat/chat-composer";
import { DirectMessageDialog } from "@/components/chat/direct-message-dialog";

export function ChatWorkspace({ initialRooms, courses, currentUserId }: { initialRooms: ChatRoomDto[]; courses: CourseDto[]; currentUserId: string }) {
  const [rooms, setRooms] = useState(initialRooms), [selected, setSelected] = useState<ChatRoomDto>();
  const [messages, setMessages] = useState<ChatMessageDto[]>([]), [text, setText] = useState(""), [reply, setReply] = useState<ChatMessageDto>();
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState<string>();
  const [directModal, setDirectModal] = useState(false);
  const [directLabels, setDirectLabels] = useState<Record<string, string>>({});
  async function load(room: ChatRoomDto, quiet = false) { if (!quiet) setLoading(true); try { const data = await clientApis.chat.listMessages(room.id, { page: 1, pageSize: 100 }); setMessages(data); const newest = data[0]; if (newest) await clientApis.chat.markAsRead(room.id, newest.id).catch(() => undefined); } catch (caught) { if (!quiet) setError(caught instanceof ApiError ? caught.detail : "Unable to load messages."); } finally { if (!quiet) setLoading(false); } }
  function select(room: ChatRoomDto) { setSelected(room); setReply(undefined); setError(undefined); void load(room); }
  useEffect(() => { if (!selected || selected.archivedAt) return; const timer = window.setInterval(() => void load(selected, true), 10000); return () => window.clearInterval(timer); }, [selected]);
  async function createCourse(courseId: string) { setBusy(true); try { const room = await clientApis.chat.getOrCreateCourseRoom(courseId); setRooms((old) => old.some((item) => item.id === room.id) ? old : [room, ...old]); select(room); } catch (caught) { setError(caught instanceof ApiError ? caught.detail : "Unable to open course chat."); } finally { setBusy(false); } }
  function directCreated(room: ChatRoomDto, user: ChatUserSearchDto) { setRooms((old) => old.some((item) => item.id === room.id) ? old : [room, ...old]); setDirectLabels((old) => ({ ...old, [room.id]: user.fullName })); setDirectModal(false); select(room); }
  async function send() { if (!selected || !text.trim()) return; setBusy(true); setError(undefined); try { const message = await clientApis.chat.sendMessage(selected.id, { content: text.trim(), replyToMessageId: reply?.id ?? null }); setMessages((old) => [message, ...old.filter((item) => item.id !== message.id)]); setText(""); setReply(undefined); } catch (caught) { setError(caught instanceof ApiError ? caught.detail : "Unable to send message."); } finally { setBusy(false); } }
  async function file(fileValue: File) { if (!selected) return; setBusy(true); setError(undefined); try { const message = await clientApis.chat.sendAttachment(selected.id, fileValue, text.trim() || null, reply?.id ?? null); setMessages((old) => [message, ...old]); setText(""); setReply(undefined); } catch (caught) { setError(caught instanceof ApiError ? caught.detail : "Unable to upload attachment."); } finally { setBusy(false); } }
  async function edit(message: ChatMessageDto) { const content = prompt("Edit message", message.content ?? ""); if (content === null || !content.trim()) return; try { const updated = await clientApis.chat.editMessage(message.id, { content: content.trim() }); setMessages((old) => old.map((item) => item.id === updated.id ? updated : item)); } catch (caught) { setError(caught instanceof ApiError ? caught.detail : "Unable to edit message."); } }
  async function remove(message: ChatMessageDto) { if (!confirm("Delete this message?")) return; try { await clientApis.chat.removeMessage(message.id); setMessages((old) => old.filter((item) => item.id !== message.id)); } catch (caught) { setError(caught instanceof ApiError ? caught.detail : "Unable to delete message."); } }
  async function download(messageId: string, attachmentId: string, fileName: string) { try { const blob = await clientApis.chat.getAttachment(messageId, attachmentId, true); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url); } catch (caught) { setError(caught instanceof ApiError ? caught.detail : "Unable to download attachment."); } }
  return <div className="space-y-3">{error ? <div className="flex items-center justify-between border border-destructive/40 bg-destructive/5 p-3 text-sm text-destructive"><span>{error}</span><button onClick={() => setError(undefined)}><X className="size-4" /></button></div> : null}<div className="grid h-[calc(100vh-13rem)] min-h-[34rem] overflow-hidden lg:grid-cols-[20rem_minmax(0,1fr)]"><div className={selected ? "hidden lg:block" : "block"}><ChatRoomList rooms={rooms} courses={courses} currentUserId={currentUserId} directLabels={directLabels} selectedId={selected?.id} onSelect={select} onCreateCourse={createCourse} onOpenDirect={() => setDirectModal(true)} /></div><section className={`${selected ? "flex" : "hidden lg:flex"} min-h-0 flex-col border border-border lg:border-l-0`}>{selected ? <><header className="flex h-16 shrink-0 items-center justify-between border-b border-border px-3 sm:px-5"><div className="flex min-w-0 items-center gap-3"><button onClick={() => setSelected(undefined)} className="p-1 lg:hidden"><ArrowLeft className="size-5" /></button><div className="min-w-0"><h2 className="truncate font-semibold">{roomLabel(selected, courses, currentUserId, directLabels)}</h2><p className="text-xs text-muted-foreground">{selected.archivedAt ? "Archived conversation" : `${selected.participantIds.length} participant${selected.participantIds.length === 1 ? "" : "s"}`}</p></div></div><MoreHorizontal className="size-5 text-muted-foreground" /></header>{loading ? <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">Loading messages…</div> : <ChatMessageList messages={messages} currentUserId={currentUserId} onReply={setReply} onEdit={edit} onDelete={remove} onDownload={download} />}<ChatComposer value={text} onChange={setText} onSend={send} onFile={file} busy={busy} disabled={Boolean(selected.archivedAt)} reply={reply} onCancelReply={() => setReply(undefined)} /></> : <div className="m-auto text-sm text-muted-foreground">Select a conversation to start messaging.</div>}</section></div>{directModal ? <DirectMessageDialog onClose={() => setDirectModal(false)} onCreated={directCreated} /> : null}</div>;
}
