"use client";

import { Download, Pencil, Reply, Trash2 } from "lucide-react";
import type { ChatMessageDto } from "@/types/api";

const formatter = new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" });
function size(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }

export function ChatMessageList({ messages, currentUserId, onReply, onEdit, onDelete, onDownload }: { messages: ChatMessageDto[]; currentUserId: string; onReply: (message: ChatMessageDto) => void; onEdit: (message: ChatMessageDto) => void; onDelete: (message: ChatMessageDto) => void; onDownload: (messageId: string, attachmentId: string, fileName: string) => void }) {
  const ordered = [...messages].reverse();
  const byId = new Map(messages.map((message) => [message.id, message]));
  return <div className="flex min-h-0 flex-1 flex-col-reverse overflow-y-auto p-3 sm:p-5"><div className="space-y-4">{ordered.length ? ordered.map((message) => { const mine = message.senderId === currentUserId; const reply = message.replyToMessageId ? byId.get(message.replyToMessageId) : undefined; return <article key={message.id} className={`group flex ${mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] sm:max-w-[75%] ${mine ? "bg-primary text-primary-foreground" : "bg-muted text-foreground"}`}><div className="px-4 py-3">{reply ? <div className={`mb-2 border-l-2 pl-2 text-xs ${mine ? "border-primary-foreground/50 text-primary-foreground/75" : "border-primary/40 text-muted-foreground"}`}>{reply.content?.slice(0, 100) || "Attachment"}</div> : null}{message.content ? <p className="whitespace-pre-wrap break-words text-sm leading-6">{message.content}</p> : null}{message.attachments.length ? <div className="mt-2 space-y-2">{message.attachments.map((attachment) => <button key={attachment.id} onClick={() => onDownload(message.id, attachment.id, attachment.fileName)} className={`flex w-full items-center gap-3 border p-2 text-left text-xs ${mine ? "border-primary-foreground/25 hover:bg-primary-foreground/10" : "border-border bg-background hover:bg-accent"}`}><Download className="size-4 shrink-0" /><span className="min-w-0 flex-1"><span className="block truncate font-medium">{attachment.fileName}</span><span className="opacity-70">{size(attachment.fileSize)}</span></span></button>)}</div> : null}<p className={`mt-2 text-[11px] ${mine ? "text-primary-foreground/65" : "text-muted-foreground"}`}>{formatter.format(new Date(message.createdAt))}{message.editedAt ? " · edited" : ""}</p></div><div className={`flex border-t opacity-100 sm:opacity-0 sm:transition sm:group-hover:opacity-100 ${mine ? "border-primary-foreground/20" : "border-border"}`}><button onClick={() => onReply(message)} className="p-2" aria-label="Reply"><Reply className="size-3.5" /></button>{mine ? <><button onClick={() => onEdit(message)} className="p-2" aria-label="Edit"><Pencil className="size-3.5" /></button><button onClick={() => onDelete(message)} className="p-2" aria-label="Delete"><Trash2 className="size-3.5" /></button></> : null}</div></div></article>; }) : <div className="py-16 text-center text-sm text-muted-foreground">No messages in this conversation. Say hello.</div>}</div></div>;
}

